### ISSUE TITLE
Implement basic simulcast

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/waterfall#31]
@daniel-abramov:

- Receive multiple spatial layers on video, forward them as a single layer.
- Let the user select the layer with `subscribe` command.

No congestion control or rate allocation for now!

**Comment by SimonBrandner** [comment]
PR: https://github.com/matrix-org/waterfall/pull/33

**Comment by dbkr** [comment]
Working on this in https://github.com/matrix-org/waterfall/pull/33

**Comment by ara4n** [comment]
what's the difference between #33 and #85?

**Comment by SimonBrandner** [comment]
> what's the difference between #33 and #85?

The former is an older PR of mine that attempted to introduce simulcast logic before the big rewrite Daniel did, while the latter is a newer Daniel's implementation
