### ISSUE TITLE
Add support for basic focus selection algorithm

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/waterfall#37]
As a temporary way of discovering SFUs, we intend to add a field to `m.call` state events called something like `im.vector.focus` which contains the matrix ID of an SFU to use for this call. A client can, in turn, get this from the .well-known of the homeserver or possibly something like /turnServer (this part we'll probably want in the long term design so this part probably wants to go in an MSC).

**Comment by dbkr** [comment]
Wait, shouldn't the event just be m.foci from the MSC?

**Comment by SimonBrandner** [comment]
> Wait, shouldn't the event just be m.foci from the MSC?

Because we won't support an array of foci but I guess we could just for now mandate an array of length 1

**Comment by dbkr** [comment]
Oh, I see - yeah, I think that's fine, and makes compatibility much easier

**Comment by SimonBrandner** [comment]
We have this now
